/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JInternalFrame;
import view.ViewLogin;
import view.ViewMobil;
import view.ViewPelanggan;
import view.ViewPeminjaman;

 /*
 * @author M S I
 */
public class ViewMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuUtama
     */
    public ViewMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnMobil = new javax.swing.JButton();
        BtnPengembalian = new javax.swing.JButton();
        BtnPelanggan = new javax.swing.JButton();
        BtnPeminjaman = new javax.swing.JButton();
        DPMenu = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("RENTAL MOBIL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        BtnMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMobil.setText("MOBIL");
        BtnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMobilActionPerformed(evt);
            }
        });

        BtnPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPengembalian.setText("PENGEMBALIAN");

        BtnPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPelanggan.setText("PELANGGAN");
        BtnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPelangganActionPerformed(evt);
            }
        });

        BtnPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPeminjaman.setText("PEMINJAMAN");
        BtnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BtnMobil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPengembalian)
                .addGap(0, 329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DPMenuLayout = new javax.swing.GroupLayout(DPMenu);
        DPMenu.setLayout(DPMenuLayout);
        DPMenuLayout.setHorizontalGroup(
            DPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        DPMenuLayout.setVerticalGroup(
            DPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPMenu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DPMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMobilActionPerformed
        // TODO add your handling code here:
        ViewMobil VM = new ViewMobil();
        VM.setVisible(true); // Tampilkan ViewMobil

        // Buat JInternalFrame dan tambahkan ViewMobil ke dalamnya
        JInternalFrame internalFrame = new JInternalFrame("View Mobil", true, true, true, true);
        internalFrame.getContentPane().add(VM);
        internalFrame.pack(); // Mengatur ukuran internalFrame sesuai dengan komponen di dalamnya
        internalFrame.setVisible(true); // Tampilkan internalFrame

        // Tambahkan internalFrame ke dalam DesktopPane
        DPMenu.add(internalFrame);
    }//GEN-LAST:event_BtnMobilActionPerformed

    private void BtnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPelangganActionPerformed
        // TODO add your handling code here:
        ViewPelanggan VP = new ViewPelanggan();
        VP.setVisible(true); // Tampilkan ViewMobil

        // Buat JInternalFrame dan tambahkan ViewMobil ke dalamnya
        JInternalFrame internalFrame = new JInternalFrame("View Mobil", true, true, true, true);
        internalFrame.getContentPane().add(VP);
        internalFrame.pack(); // Mengatur ukuran internalFrame sesuai dengan komponen di dalamnya
        internalFrame.setVisible(true); // Tampilkan internalFrame

        // Tambahkan internalFrame ke dalam DesktopPane
        DPMenu.add(internalFrame);
    }//GEN-LAST:event_BtnPelangganActionPerformed

    private void BtnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMobil;
    private javax.swing.JButton BtnPelanggan;
    private javax.swing.JButton BtnPeminjaman;
    private javax.swing.JButton BtnPengembalian;
    private javax.swing.JDesktopPane DPMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
