/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.Koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.ViewLogin;
import view.ViewMobil;
import view.ViewPelanggan;
import view.ViewPeminjaman;

 /*
 * @author M S I
 */
public class ViewMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuUtama
     */
    private DefaultTableModel tbmodel;
    
    public ViewMenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tbmodel = new DefaultTableModel();
        TBTransaksi.setModel(tbmodel);
  
        tampilDataPeminjaman();
    }
    
    public void tampilDataPeminjaman() {
    try {
        // Mendapatkan objek koneksi dari kelas Koneksi
        Koneksi connect = new Koneksi();

        String[] kolom = {"ID PEMINJAMAN", "ID MOBIL", "ID PELANGGAN", "TGL SEWA", "TGL KEMBALI", "TOTAL HARGA", "STATUS"};
        tbmodel.setColumnIdentifiers(kolom);

        // Menghapus data yang ada di tabel
        tbmodel.setRowCount(0);

        String sql = "SELECT * FROM peminjaman";

        PreparedStatement statement = connect.getConnection().prepareStatement(sql);
        ResultSet result = statement.executeQuery();

        while (result.next()) {
            int id_peminjama = result.getInt("id_peminjaman");
            int id_pelanggan = result.getInt("id_pelanggan");
            int id_mobil = result.getInt("id_mobil");
            String tgl_sewa = result.getString("tgl_sewa");
            String tgl_kembali = result.getString("tgl_kembali");
            int total_harga = result.getInt("total_harga");
            String status = result.getString("status");


            Object[] data = {id_peminjama, id_pelanggan, id_mobil, tgl_sewa, tgl_kembali, total_harga,status};
            tbmodel.addRow(data);
        }

        statement.close();
        result.close();
        connect.getConnection().close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Gagal mendapatkan data: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnMobil = new javax.swing.JButton();
        BtnPengembalian = new javax.swing.JButton();
        BtnPelanggan = new javax.swing.JButton();
        BtnPeminjaman = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("RENTAL MOBIL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        BtnMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMobil.setText("MOBIL");
        BtnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMobilActionPerformed(evt);
            }
        });

        BtnPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPengembalian.setText("PENGEMBALIAN");

        BtnPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPelanggan.setText("PELANGGAN");
        BtnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPelangganActionPerformed(evt);
            }
        });

        BtnPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPeminjaman.setText("PEMINJAMAN");
        BtnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BtnMobil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPengembalian)
                .addGap(0, 502, Short.MAX_VALUE))
        );

        TBTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PEMINJAMAN", "ID MOBIL", "ID PELANGGAN", "TGL SEWA", "TGL KEMBALI", "TOTAL HARGA", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(TBTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMobilActionPerformed
        // TODO add your handling code here:
        ViewMobil VM = new ViewMobil();
        VM.setVisible(true); // Tampilkan ViewMobil

//        // Buat JInternalFrame dan tambahkan ViewMobil ke dalamnya
//        JInternalFrame internalFrame = new JInternalFrame("View Mobil", true, true, true, true);
//        internalFrame.getContentPane().add(VM);
//        internalFrame.pack(); // Mengatur ukuran internalFrame sesuai dengan komponen di dalamnya
//        internalFrame.setVisible(true); // Tampilkan internalFrame
//
//        // Tambahkan internalFrame ke dalam DesktopPane
//        DPMenu.add(internalFrame);
    }//GEN-LAST:event_BtnMobilActionPerformed

    private void BtnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPelangganActionPerformed
        // TODO add your handling code here:
        ViewPelanggan VP = new ViewPelanggan();
        VP.setVisible(true); // Tampilkan ViewMobil

//        // Buat JInternalFrame dan tambahkan ViewMobil ke dalamnya
//        JInternalFrame internalFrame = new JInternalFrame("View Mobil", true, true, true, true);
//        internalFrame.getContentPane().add(VP);
//        internalFrame.pack(); // Mengatur ukuran internalFrame sesuai dengan komponen di dalamnya
//        internalFrame.setVisible(true); // Tampilkan internalFrame
//
//        // Tambahkan internalFrame ke dalam DesktopPane
//        DPMenu.add(internalFrame);
    }//GEN-LAST:event_BtnPelangganActionPerformed

    private void BtnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeminjamanActionPerformed
        // TODO add your handling code here:
        ViewPeminjaman VPp = new ViewPeminjaman();
        VPp.setVisible(true); // Tampilkan ViewMobil
    }//GEN-LAST:event_BtnPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMobil;
    private javax.swing.JButton BtnPelanggan;
    private javax.swing.JButton BtnPeminjaman;
    private javax.swing.JButton BtnPengembalian;
    private javax.swing.JTable TBTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
